name: Android Build and Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        default: false

# Add permissions needed for creating releases
permissions:
  contents: write
  packages: read

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Variables
        run: |
          echo VERSION=$(npm run get-version --silent) >> $GITHUB_ENV
        shell: bash
    
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Cargo-mobile2
        run: |
          cargo install cargo-mobile2
          cargo mobile init

      - name: Install dependencies
        run: npm install

      - name: Build Android app
        run: |
          cargo mobile android build --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.VERSION }}-android
          name: "Nostria Signer v${{ env.VERSION }} for Android"
          draft: true
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            target/mobile/android/app/build/outputs/apk/release/*.apk
            target/mobile/android/app/build/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-android
          path: |
            target/mobile/android/app/build/outputs/apk/release/*.apk
            target/mobile/android/app/build/outputs/bundle/release/*.aab
